//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDbtDiaryCard.Resx {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DbtSkillsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbtSkillsResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDbtDiaryCard.Resx.DbtSkillsResources", typeof(DbtSkillsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ACCEPT.
        /// </summary>
        public static string D_Accept {
            get {
                return ResourceManager.GetString("D_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IMPROVE The Moment.
        /// </summary>
        public static string D_ImproveTheMoment {
            get {
                return ResourceManager.GetString("D_ImproveTheMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pros and Cons.
        /// </summary>
        public static string D_ProsAndCons {
            get {
                return ResourceManager.GetString("D_ProsAndCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radical Acceptance.
        /// </summary>
        public static string D_RadicalAcceptance {
            get {
                return ResourceManager.GetString("D_RadicalAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Self Soothe.
        /// </summary>
        public static string D_SelfSoothe {
            get {
                return ResourceManager.GetString("D_SelfSoothe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на STOP.
        /// </summary>
        public static string D_STOP {
            get {
                return ResourceManager.GetString("D_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TIPP.
        /// </summary>
        public static string D_TIPP {
            get {
                return ResourceManager.GetString("D_TIPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Willingness and HalfSmile.
        /// </summary>
        public static string D_WillingnessAndHalfSmile {
            get {
                return ResourceManager.GetString("D_WillingnessAndHalfSmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check The Facts.
        /// </summary>
        public static string E_CheckTheFacts {
            get {
                return ResourceManager.GetString("E_CheckTheFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Labeling Emotions.
        /// </summary>
        public static string E_LabelingEmotions {
            get {
                return ResourceManager.GetString("E_LabelingEmotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opposite Action.
        /// </summary>
        public static string E_Opposite_Action {
            get {
                return ResourceManager.GetString("E_Opposite Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PLEASE.
        /// </summary>
        public static string E_Please {
            get {
                return ResourceManager.GetString("E_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Promlrm sloving.
        /// </summary>
        public static string E_ProblemSloving {
            get {
                return ResourceManager.GetString("E_ProblemSloving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Describe.
        /// </summary>
        public static string M_Describe {
            get {
                return ResourceManager.GetString("M_Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Effectively.
        /// </summary>
        public static string M_Effectively {
            get {
                return ResourceManager.GetString("M_Effectively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle Path.
        /// </summary>
        public static string M_MiddlePath {
            get {
                return ResourceManager.GetString("M_MiddlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Non Judgmentally.
        /// </summary>
        public static string M_NonJudgmentally {
            get {
                return ResourceManager.GetString("M_NonJudgmentally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Observe.
        /// </summary>
        public static string M_Observe {
            get {
                return ResourceManager.GetString("M_Observe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One Mindfully.
        /// </summary>
        public static string M_OneMindfully {
            get {
                return ResourceManager.GetString("M_OneMindfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Participate.
        /// </summary>
        public static string M_Participate {
            get {
                return ResourceManager.GetString("M_Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wise Mind.
        /// </summary>
        public static string M_WiseMind {
            get {
                return ResourceManager.GetString("M_WiseMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Distress Tolerance.
        /// </summary>
        public static string Module_DistressTolerance {
            get {
                return ResourceManager.GetString("Module_DistressTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EmotionRegulation.
        /// </summary>
        public static string Module_EmotionRegulation {
            get {
                return ResourceManager.GetString("Module_EmotionRegulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на InterpersonalEffectiveness.
        /// </summary>
        public static string Module_InterpersonalEffectiveness {
            get {
                return ResourceManager.GetString("Module_InterpersonalEffectiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mindfulness.
        /// </summary>
        public static string Module_Mindfulness {
            get {
                return ResourceManager.GetString("Module_Mindfulness", resourceCulture);
            }
        }
    }
}
