//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDbtDiaryCard.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DbtSkillsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbtSkillsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDbtDiaryCard.Resx.DbtSkillsResources", typeof(DbtSkillsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCEPT.
        /// </summary>
        public static string D_Accept {
            get {
                return ResourceManager.GetString("D_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPROVE The Moment.
        /// </summary>
        public static string D_ImproveTheMoment {
            get {
                return ResourceManager.GetString("D_ImproveTheMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pros and Cons.
        /// </summary>
        public static string D_ProsAndCons {
            get {
                return ResourceManager.GetString("D_ProsAndCons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radical Acceptance.
        /// </summary>
        public static string D_RadicalAcceptance {
            get {
                return ResourceManager.GetString("D_RadicalAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Soothe.
        /// </summary>
        public static string D_SelfSoothe {
            get {
                return ResourceManager.GetString("D_SelfSoothe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        public static string D_STOP {
            get {
                return ResourceManager.GetString("D_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIPP.
        /// </summary>
        public static string D_TIPP {
            get {
                return ResourceManager.GetString("D_TIPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willingness and HalfSmile.
        /// </summary>
        public static string D_WillingnessAndHalfSmile {
            get {
                return ResourceManager.GetString("D_WillingnessAndHalfSmile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Positive Emotions.
        /// </summary>
        public static string E_AccumulatePositiveEmotions {
            get {
                return ResourceManager.GetString("E_AccumulatePositiveEmotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Mastery.
        /// </summary>
        public static string E_BuildMastery {
            get {
                return ResourceManager.GetString("E_BuildMastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check The Facts.
        /// </summary>
        public static string E_CheckTheFacts {
            get {
                return ResourceManager.GetString("E_CheckTheFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cope Ahead.
        /// </summary>
        public static string E_CopeAhead {
            get {
                return ResourceManager.GetString("E_CopeAhead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labeling Emotions.
        /// </summary>
        public static string E_LabelingEmotions {
            get {
                return ResourceManager.GetString("E_LabelingEmotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opposite Action.
        /// </summary>
        public static string E_Opposite_Action {
            get {
                return ResourceManager.GetString("E_Opposite Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE.
        /// </summary>
        public static string E_Please {
            get {
                return ResourceManager.GetString("E_Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem sloving.
        /// </summary>
        public static string E_ProblemSloving {
            get {
                return ResourceManager.GetString("E_ProblemSloving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEAR.
        /// </summary>
        public static string I_Dear {
            get {
                return ResourceManager.GetString("I_Dear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAST.
        /// </summary>
        public static string I_Fast {
            get {
                return ResourceManager.GetString("I_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIVE.
        /// </summary>
        public static string I_Give {
            get {
                return ResourceManager.GetString("I_Give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAN.
        /// </summary>
        public static string I_Man {
            get {
                return ResourceManager.GetString("I_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string I_Validation {
            get {
                return ResourceManager.GetString("I_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe.
        /// </summary>
        public static string M_Describe {
            get {
                return ResourceManager.GetString("M_Describe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effectively.
        /// </summary>
        public static string M_Effectively {
            get {
                return ResourceManager.GetString("M_Effectively", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Path.
        /// </summary>
        public static string M_MiddlePath {
            get {
                return ResourceManager.GetString("M_MiddlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Judgmentally.
        /// </summary>
        public static string M_NonJudgmentally {
            get {
                return ResourceManager.GetString("M_NonJudgmentally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observe.
        /// </summary>
        public static string M_Observe {
            get {
                return ResourceManager.GetString("M_Observe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Mindfully.
        /// </summary>
        public static string M_OneMindfully {
            get {
                return ResourceManager.GetString("M_OneMindfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate.
        /// </summary>
        public static string M_Participate {
            get {
                return ResourceManager.GetString("M_Participate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wise Mind.
        /// </summary>
        public static string M_WiseMind {
            get {
                return ResourceManager.GetString("M_WiseMind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distress Tolerance.
        /// </summary>
        public static string Module_DistressTolerance {
            get {
                return ResourceManager.GetString("Module_DistressTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmotionRegulation.
        /// </summary>
        public static string Module_EmotionRegulation {
            get {
                return ResourceManager.GetString("Module_EmotionRegulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpersonal Effectiveness.
        /// </summary>
        public static string Module_InterpersonalEffectiveness {
            get {
                return ResourceManager.GetString("Module_InterpersonalEffectiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mindfulness.
        /// </summary>
        public static string Module_Mindfulness {
            get {
                return ResourceManager.GetString("Module_Mindfulness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Module_Tools {
            get {
                return ResourceManager.GetString("Module_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Analysis.
        /// </summary>
        public static string T_ChainAnalysis {
            get {
                return ResourceManager.GetString("T_ChainAnalysis", resourceCulture);
            }
        }
    }
}
