//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDbtDiaryCard.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyDbtDiaryCard.Resx.EntryResources", typeof(EntryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        internal static string Additional {
            get {
                return ResourceManager.GetString("Additional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anger.
        /// </summary>
        internal static string E_Anger {
            get {
                return ResourceManager.GetString("E_Anger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fear.
        /// </summary>
        internal static string E_Fear {
            get {
                return ResourceManager.GetString("E_Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joy.
        /// </summary>
        internal static string E_Joy {
            get {
                return ResourceManager.GetString("E_Joy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pride.
        /// </summary>
        internal static string E_Pride {
            get {
                return ResourceManager.GetString("E_Pride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sadness.
        /// </summary>
        internal static string E_Sadness {
            get {
                return ResourceManager.GetString("E_Sadness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shame.
        /// </summary>
        internal static string E_Shame {
            get {
                return ResourceManager.GetString("E_Shame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotions.
        /// </summary>
        internal static string Emotions {
            get {
                return ResourceManager.GetString("Emotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotion misery.
        /// </summary>
        internal static string F_EmotionMisery {
            get {
                return ResourceManager.GetString("F_EmotionMisery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excitation.
        /// </summary>
        internal static string F_Excitation {
            get {
                return ResourceManager.GetString("F_Excitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical misery.
        /// </summary>
        internal static string F_PhysicalMisery {
            get {
                return ResourceManager.GetString("F_PhysicalMisery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feelings.
        /// </summary>
        internal static string Feelings {
            get {
                return ResourceManager.GetString("Feelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meds.
        /// </summary>
        internal static string Meds {
            get {
                return ResourceManager.GetString("Meds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        internal static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol.
        /// </summary>
        internal static string U_Alcohol {
            get {
                return ResourceManager.GetString("U_Alcohol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        internal static string U_Drugs {
            get {
                return ResourceManager.GetString("U_Drugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelfHarm.
        /// </summary>
        internal static string U_SelfHarm {
            get {
                return ResourceManager.GetString("U_SelfHarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suicide.
        /// </summary>
        internal static string U_Suicide {
            get {
                return ResourceManager.GetString("U_Suicide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urges.
        /// </summary>
        internal static string Urges {
            get {
                return ResourceManager.GetString("Urges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usefulness.
        /// </summary>
        internal static string Usefulness {
            get {
                return ResourceManager.GetString("Usefulness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - Not thought about or used.
        /// </summary>
        internal static string Usefulness_0 {
            get {
                return ResourceManager.GetString("Usefulness_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Thought about, not used, didn’t want to.
        /// </summary>
        internal static string Usefulness_1 {
            get {
                return ResourceManager.GetString("Usefulness_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Thought about, not used, wanted to.
        /// </summary>
        internal static string Usefulness_2 {
            get {
                return ResourceManager.GetString("Usefulness_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Tried but couldn’t use them.
        /// </summary>
        internal static string Usefulness_3 {
            get {
                return ResourceManager.GetString("Usefulness_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Tried, could do them but they didn’t help.
        /// </summary>
        internal static string Usefulness_4 {
            get {
                return ResourceManager.GetString("Usefulness_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Tried, could use them, helped.
        /// </summary>
        internal static string Usefulness_5 {
            get {
                return ResourceManager.GetString("Usefulness_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Didn’t try, used them, didn’t help.
        /// </summary>
        internal static string Usefulness_6 {
            get {
                return ResourceManager.GetString("Usefulness_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 - Didn’t try, used them, helped.
        /// </summary>
        internal static string Usefulness_7 {
            get {
                return ResourceManager.GetString("Usefulness_7", resourceCulture);
            }
        }
    }
}
